config/routes.rb
Rails.application.routes.draw do
  resources :registrations

  post "/hook" => "registrations#hook"
  post "/registrations/:id" => "registrations#show"

  resources :courses

  root "courses#index"
end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :course

  validates :full_name, :company, :email, :telephone, presence: true

  serialize :notification_params, Hash
  def paypal_url(return_path)
    values = {
        business: "merchant@gotealeaf.com",
        cmd: "_xclick",
        upload: 1,
        return: "#{Rails.application.secrets.app_host}#{return_path}",
        invoice: id,
        amount: course.price,
        item_name: course.name,
        item_number: course.id,
        quantity: '1',
        notify_url: "#{Rails.application.secrets.app_host}/hook"
    }
    "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :get_courses

  def get_courses
    @courses = Course.last(1)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  layout "application"

  # GET /courses
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :set_registration, only: [:show, :edit, :update, :destroy]

  # GET /registrations
  def index
    @registrations = Registration.all
  end

  # GET /registrations/1
  def show
  end

  # GET /registrations/new
  def new
    @registration = Registration.new
    @course = Course.find_by id: params["course_id"]
  end

  # POST /registrations
  def create
    @registration = Registration.new(registration_params)
    if @registration.save
      redirect_to @registration.paypal_url(registration_path(@registration))
    else
      render :new
    end
  end

  protect_from_forgery except: [:hook]
  def hook
    params.permit! # Permit all Paypal input params
    status = params[:payment_status]
    if status == "Completed"
      @registration = Registration.find params[:invoice]
      @registration.update_attributes notification_params: params, status: status, transaction_id: params[:txn_id], purchased_at: Time.now
    end
    render nothing: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registration
      @registration = Registration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registration_params
      params.require(:registration).permit(:course_id, :full_name, :company, :email, :telephone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_index.html.haml
.course-nav-wrapper
  .wrapper-inside.clearfix
    %ul.course-nav-list
      - @courses.each do |course|
        %li{class: "#{"active" if params["course_id"].to_i== course.id}"}
          = link_to new_registration_path(course_id: course.id), class: "ruby" do
            .course-name
              = course.name

            %button.btn{style: "color: white;background: rgb(242, 118, 73);"} Register ($#{course.price})
            .course-arrow

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title PaypalBasics
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %link{:href => "http://fonts.googleapis.com/css?family=Crete+Round:400,400italic|Open+Sans:400,700,800", :rel => "stylesheet"}/
    = csrf_meta_tags
  %body.curriculum-page
    .wrapper
      %header#header
        .top-bg
          .wrapper-inside.clearfix
            %h1#logo
              %a{:href => "/"} Flying Cakes
              .sub The Cookery School
            %nav.nav
              %ul
                %li
                  %a{:href => "/faq"} FAQ
                %li
                  %a.current{:href => "/curriculum"} Curriculum
                %li
                  %a{:href => "/success_stories"} Success Stories
                %li
                  %a.apply{"data-toggle" => "modal", :href => "#get_started"} Send Me Details Now!
                %li
                  %a{:href => "/sign_in"} Student Login
        .wrapper-inside.clearfix
          .top-small The 3-Course Professional Grade Curriculum
      %section.content.clearfix
        %section.curriculum
          = render partial: "courses/index"
          = yield